spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/testdb?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul
    username: postgres
    password: root

#logging:
#  level:
#    com:
#      wizard:
#        pracmybatis:
#          repository: DEBUG