DELIMITER $$

DROP FUNCTION IF EXISTS UserTypeGuest;

CREATE FUNCTION UserTypeGuest() RETURNS int(11)
BEGIN
  RETURN 1;
END;

DROP FUNCTION IF EXISTS UserTypeMember;

CREATE FUNCTION UserTypeMember() RETURNS int(11)
BEGIN
  RETURN 2;
END;

DROP FUNCTION IF EXISTS UserTypeSuper;

CREATE FUNCTION UserTypeSuper() RETURNS int(11)
BEGIN
  RETURN 99;
END;

$$
DELIMITER ;
